font_family               DejaVuSansM Nerd Font

wayland_titlebar_color    system
hide_window_decorations   yes

background                #ffffff
foreground                #000000

selection_background      #b4d5ff
selection_foreground      #ffffff

cursor                    none

active_tab_foreground     #2E3436
active_tab_background     #FEFEFE

inactive_tab_foreground   #06989A
inactive_tab_background   #DFDFDF
tab_bar_background        #CBCBCB

color0                    #000000
color1                    #cc0000
color2                    #4e9a05
color3                    #c4a000
color4                    #3464a4
color5                    #74507a
color6                    #05989a
color7                    #d3d7cf
color8                    #545753
color9                    #ef2828
color10                   #8ae234
color11                   #fce94e
color12                   #719ecf
color13                   #ad7ea7
color14                   #34e2e2
color15                   #ededec

background_opacity        0.9
cursor_blink_interval     0

tab_bar_edge              top
tab_bar_style             separator
tab_separator             "    ⁞    "

active_tab_font_style     bold-italic
inactive_tab_font_style   normal

repaint_delay             8
input_delay               0

sync_to_monitor           no
scrollback_lines          20000

map     ctrl+shift+t      new_tab
map     ctrl+shift+w      close_tab
map     ctrl+shift+tab    prev_tab
map     ctrl+tab          next_tab
map     ctrl+shift+f      toggle_fullscreen
