font_family DejaVuSansM Nerd Font

wayland_titlebar_color system
hide_window_decorations yes

background #ffffff
foreground #000000
cursor #000000
selection_background #b4d5ff
color0 #000000
color8 #545753
color1 #cc0000
color9 #ef2828
color2 #4e9a05
color10 #8ae234
color3 #c4a000
color11 #fce94e
color4 #3464a4
color12 #719ecf
color5 #74507a
color13 #ad7ea7
color6 #05989a
color14 #34e2e2
color7 #d3d7cf
color15 #ededec
selection_foreground #ffffff

background_opacity 0.9

cursor none
cursor_blink_interval 0

repaint_delay 8
input_delay 0

sync_to_monitor no
scrollback_lines 20000

map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+tab prev_tab
map ctrl+tab next_tab

map ctrl+shift+f toggle_fullscreen

tab_bar_edge top
tab_bar_style separator
tab_separator "    ⁞    "
tab_bar_background #CBCBCB

active_tab_foreground   #2E3436
active_tab_background   #FEFEFE
active_tab_font_style   bold-italic
inactive_tab_foreground #06989A
inactive_tab_background #DFDFDF
inactive_tab_font_style normal
