#  NOTE:───────────────────────────────────────────────────────────────────────┐
#  │                                                                           │
#  │ ~/.tmux.conf                                                              │
#  │                                                                           │
#  │ - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm       │
#  │                                                                           │
#  │ - lazy install: `<C-b><S-i>`                                              │
#  │ - lazy update: `<C-b><S-u>`                                               │
#  │ - lazy clean: `<C-b><M-u>`                                                │
#  └───────────────────────────────────────────────────────────────────────────┘

set -g detach-on-destroy off
set -g history-limit 10000
set -s escape-time 0
set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

setw -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ┌────────────┐
# │ Statusline │
# └────────────┘

set -g status-bg "colour15"
set -g status-fg "colour0"
set -g status-position top

set -g message-style bg="colour15",fg="colour0 bold"
set -g mode-style bg="colour15",fg="colour0 bold"

# 'jtmcginty/tmux-session-dots' settings
set -g status-right "#{session_dots}%H:%M %p"

set -g @session-dots-active "󰄯 "
set -g @session-dots-inactive "󱥸 "
set -g @session-dots-color default

# ┌────────────────────┐
# │ Session Management │
# └────────────────────┘

bind h switch-client -p
bind l switch-client -n
bind L switch-client -l

bind a command-prompt -p "Create session" "new-session -s '%%'"
bind q confirm-before -p "Kill session #S? (y/N)" kill-session

# ┌─────────────────────┐
# │ TMUX Plugin Manager │
# └─────────────────────┘

set -g @plugin 'jtmcginty/tmux-session-dots'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'
